### ISSUE TITLE
cp: permission denied

### ISSUE THREAD

**Issue by jduthen** [egold/better-xcode-ibeam-cursor#10]
$ cp $XCODE_RESOURCE_PATH/DVTIbeamCursor.tiff $XCODE_RESOURCE_PATH/backup-DVTIbeamCursor.tiff
cp: /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Resources/backup-DVTIbeamCursor.tiff: Permission denied

I would prefer:
sudo mv $XCODE_RESOURCE_PATH/DVTIbeamCursor.tiff $XCODE_RESOURCE_PATH/backup-DVTIbeamCursor.tiff

**Comment by jeeeyul** [comment]
I faced same problem. (OS 10.11 beta2)

**Comment by egold** [comment]
Hey @jduthen or @jeeeyul -- can you update the install script and submit a pull request? Would love to have you has a contributor to this project!

**Comment by egold** [comment]
Kudos to @jameszaghini for contributing to the code to fix the issue others reported!
