### ISSUE TITLE
Xcode 8 beta

### ISSUE THREAD

**Issue by macintacos** [egold/better-xcode-ibeam-cursor#18]
This is probably entirely too early in the game to be requesting this, but getting the patch to work on Xcode 8 would be awesome

**Comment by mzarra** [comment]
Copying the file from Xcode to Xcode-beta worked for me.

Run the `install.sh` script then:

    cp /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Resources/Assets.car /Applications/Xcode-beta.app/Contents/SharedFrameworks/DVTKit.framework/Resources/Assets.car

**Comment by macintacos** [comment]
@mzarra Worked perfectly, thanks.
