### ISSUE TITLE
Cursor is too large!

### ISSUE THREAD

**Issue by 7stud** [egold/better-xcode-ibeam-cursor#7]
Hi,

I used your .tiff file with Mousecape to create an Ibeam cursor that I could see while hovering over a black Terminal window(Pro style).  However, your .tiff image creates a cursor that is about 10 times the size of the normal Ibeam cursor.   Is the Ibeam gargantuan in Xcode as well?

Aha!  The solution is to drag the .tiff file onto the box labeled '2x' in Mousecape.

**Comment by egold** [comment]
Yeah, glad you figured that out. This project wasn't intended to work with any other third party solution for mouse cursor customization. Thanks.
